### ISSUE TITLE
It is need to use load()?

### ISSUE THREAD

**Issue by denizzzka** [mdparker/Derelict3#128]
I am see a static constructors which something to loads.
I still should use load() ? In which cases I should use it?

Example:

import derelict.sfml2.systemtypes;
import derelict.sfml2.system;
import derelict.sfml2.windowtypes;
import derelict.sfml2.window;
import derelict.sfml2.graphicstypes;
import derelict.sfml2.graphics;

import std.string: toStringz;
import std.stdio;

void main()
{
    //DerelictSFML2System.load();
    //DerelictSFML2Window.load();
    DerelictSFML2Graphics.load(); // need to be uncommented to prevent core dump

```
sfVideoMode vmode = { width: 640, height: 480, bitsPerPixel: 24 };
sfContextSettings settings = { depthBits: 24,
                               stencilBits: 1,
                               antialiasingLevel: 1,
                               minorVersion: 1,
                               majorVersion: 2 };


const char* title = toStringz("hello");

auto ptr = sfRenderWindow_create(
    vmode,
    title,
    sfDefaultStyle,
    &settings
);

sfRenderWindow_display( ptr ); // screen blinks

//while(true){}
```

}

**Comment by mdparker** [comment]
I don't know what static constructors you are talking about. You need to call the load methods in order to load the functions of any shared library you intend to use. In this case, since you don't need to call any functions from sfml2.system or sfml2.window, then you don't need to call load for them. Also, you do not need to import the *types modules. Those are already publicly imported (for example, importing derelict.sfml2.system also imports systemtypes).

From now on, please don't use this issue tracker for help. This is for bug reports and enhancement requests. If you need help, please go to the Derelict forum at http://dblog.aldacron.net/forum/index.php, create an account, and ask your questions there. If you have any trouble with the account creation, just email me and I will get you set up.
