### ISSUE TITLE
glxext.h missing declerations

### ISSUE THREAD

**Issue by rikkimax** [mdparker/Derelict3#129]
It appears glext.h has not been added yet.
http://www.opengl.org/registry/api/GL/glxext.h

I can have a go at the constants as thats stopping me for a project if you want.

**Comment by mdparker** [comment]
glext.h or glxext.h? Your title and comment mention the former, but your link is pointing to the latter. If it's the latter, it's intentional. I never implemented it for Derelict 2 either and have no desire to go mucking about in Linux to test it now. I'd happily accept a pull request for the whole thing, constants and functions, though. If it's the former, tell me which missing extensions you need and I'll see about implementing them.

**Comment by rikkimax** [comment]
Sorry I did mean glxext.
I found out that its more than just constants I do need.

I'll have a go at doing the whole thing.
