### ISSUE TITLE
Time to change the readme?

### ISSUE THREAD

**Issue by John-Colvin** [mdparker/Derelict3#138]
On github, the readme forms a big part of the first impression of a project. The current readme doesn't make a great impression.

The current readme starts on a bit of a downer and then talks about derelict 1 and 2. This transition information is useful, but doesn't deserve the priority position it has. It does not serve well to enthuse or encourage new users to try the library or D in general.

Time for a bit of a marketing overhaul?

**Comment by mdparker** [comment]
I don't think of it that way. This is just a library that I've put up for people to use. I don't care if they do or not and feel no particular need to "market" it. Never been formal with Derelict and never intend to. I want to keep it as casual as possible and give the exact opposite impression of being professional, because that would ultimately demand more of my time. Too much work.

Of course, if there's anything blatantly wrong with readme, then I'll change it. And I do intend to put some documentation up on the project Wiki eventually, at which point I'll trim the readme down to a paragraph or two. That said, what sort of changes do you have in mind? What part is a downer? The bit that it's an alpha? Or something else?

**Comment by John-Colvin** [comment]
I make a quick example of what I feel would be better: https://github.com/aldacron/Derelict3/pull/144
