### ISSUE TITLE
Incomplete wglext

### ISSUE THREAD

**Issue by rikkimax** [mdparker/Derelict3#152]
This is more of a note for me to commit to making sure this is up to date.
Discovered so far wglSwapIntervalEXT is missing.
http://www.opengl.org/registry/api/GL/wglext.h

**Comment by mdparker** [comment]
Yeah, I only implemented the ARB stuff. This is an important one, though.

My position is, I don't believe we should worry about the rest of them. Many of those extensions are rarely used. We can add them as and when they're needed. But if you want to implement the, I'll have no problem accepting a pull request for it.

I'll take care of wglSwapIntervalEXT right now.

**Comment by rikkimax** [comment]
Thanks.
I do want to have complete bindings to the headers though as a more just in case for others in the future.
Its not really big at any rate and most of its already there.

**Comment by rikkimax** [comment]
I'm currently creating wrappers around opengl functions to make a bit more usable e.g. D arrays and enums for values.
I've noticed a few things missing up to opengl 1.5 so far.
glGetQueryObjecti64v, glGetQueryObjectui64v and GL_QUERY_BUFFER.
So when I finally get round to dealing with all this I'll also look over the rest of the headers as well.

**Comment by mdparker** [comment]
The specific items you mentioned are not missing. They belong to the ARB_timer_query extenstion and, as such, are declared in arb.d. ARB_timer_query became part of the core specification in version 3.3, so in gl3.d on line 356, you'll find a call to load_ARB_timer_query if the context supports version 3.3 or greater. For version 3+, you'll find a lot of that. ARB extensions are absorbed into the core as-is. The way I handle it is to load those extensions with the appropriate GL version if that version is supported by the context, in which case an exception will be thrown if any of the symbols are missing. Otherwise, they are loaded as part of the internal call to loadARB, in which case no exception is thrown if any of the symbols are missing, but a flag for that extension is set to false. So if you see anything missing from functions.d or constants.d, look in arb.d.

**Comment by rikkimax** [comment]
Ah ok thanks, explains why IDE couldn't find it.
However GL_QUERY_BUFFER is definitely not in my local copy. Which could be out of date if its been added since I cloned.

**Comment by mdparker** [comment]
GL_QUERY_BUFFER is part of the ARB_query_buffer_object extension which was approved in June and added to the core in version 4.4. I have not updated to any that stuff yet. I'll get around to it eventually.

In the meantime, if you could use the forums for this sort of thing, I'd appreciate it. It has nothing to do with the original issue you posted here.

Also, as I'm transitioning everything over to the new [DerelictOrg](https://github.com/DerelictOrg), you might want to base your work off of the DerelictGL3 repo over there.

**Comment by rikkimax** [comment]
Sorry, the only reason I added it here was to mention that I would look at it at the same time and why.
I'll close this and deal with fixing it in other repo.
