### ISSUE TITLE
Shared lib support disapear

### ISSUE THREAD

**Issue by bioinfornatics** [mdparker/Derelict3#154]
Hi, before we was able to build as shared lib by using  `-d-version=Shared`
Fedora package use only shared lib.

``` d
else version(LDC)
{
    pragma(msg, "Using the LDC compiler.");
    version(Shared) enum compilerOptions = "-shared -O -release -enable-inlining -property -w -wi";
    else enum compilerOptions = "-lib -O -release -enable-inlining -property -w -wi";
    string buildCompileString(string files, string libName)
    {
        version(Shared)
            return format("ldc2 %s -soname=%s.%s -I../import -of%s%s.%s %s", compilerOptions, libName, MajorVersion, outdir, libName, FullVersion, files);
        else
            return format("ldc2 %s -I../import -of%s%s %s", compilerOptions, outdir, libName, files);
    }
}
```

**Comment by mdparker** [comment]
Yes, I removed it from the build script. I decided that I didn't want versioned shared libraries out there, since Derelict is not versioned. It doesn't matter anyway, because soon I'm going to remove the build script completely. I'll be splitting Derelict up into one repository per package and will depend on dub.

**Comment by bioinfornatics** [comment]
oh no
dub is for user but not for packaging

**Comment by mdparker** [comment]
Sorry. I just don't see the point in maintaining something like that for only one platform. And having two separate compilation commands for shared vs. static libs made updating the build script a little annoying.

I don't see that Derelict needs to be packaged as RPMs or DEBs anyway. Since dub works on Linux just as well as on Windows, there's no need for packaging.
