### ISSUE TITLE
PostgreSQL pq DUB integration

### ISSUE THREAD

**Issue by ilya-stromberg** [mdparker/Derelict3#162]
Please, move PostgreSQL pq library to the DerelictOrg repository, add DUB package.json and register it in the DUB central package registry.

You can use my fork of the Derelict3 pq project, I only add package.json and    .gitignore files:
https://github.com/ilya-stromberg/DerelictPQ

I hope it helps. Thanks.

**Comment by mdparker** [comment]
It's on my TODO list, along with most of the other packages.

**Comment by mdparker** [comment]
FYI, I've migrated DerelictPQ over to DerelictOrg now. If you are using a libpq version < 9.3, it will break. You'll have to use the selective loading mechanism to load lower versions. I only realized when migrating that the original implementation in this repository was special casing versions 9.1 and 9.2. That really is inconsistent with the rest of Derelict, so I changed it for the DerelictOrg version. I also removed the loadedVersion method from DerelictPQ, since it isn't necessary.
