### ISSUE TITLE
How about a stable release?

### ISSUE THREAD

**Issue by svenstaro** [mdparker/Derelict3#21]
Derelict3 seems fairly stable for me. Why not make a release? It's not it's going to change a lot or anything. It's just a bunch of bindings.

**Comment by mdparker** [comment]
For a collection of bindings, I don't even know what that means. After a "release" very early on several years back, I've never bothered with it. Currently, I call it "alpha" simply because there's no documentation and I've still got a few more touches I want to add. Once that's all done, I'll call it stable, but I won't do any releases.
