### ISSUE TITLE
Where glu* functions?

### ISSUE THREAD

**Issue by ghowland** [mdparker/Derelict3#45]
I dont see the GLU functions being bound, like gluPerspective().  Is there a reason they arent included in Derelict3?

**Comment by mdparker** [comment]
Yes. Because Derelict 3 is intended to be a binding to modern OpenGL, without the deprecated stuff. GLU is deprecated. I added a binding for some of the deprecated GL functions after a few requests, but I have no plans to add GLU bindings.

The vast majority of GLU usage that I've seen is for functionality that is easily implemented yourself (gluOrtho2D, gluLookAt and such). If you absolutely need GLU and can't implement the particular functionality yourself, then you'll have to use Derelict 2.

**Comment by ghowland** [comment]
Cool
